"""Streamlit entry point for the MandiMind PoC."""
import streamlit as st
from agent.agent import MandiMindAgent

st.set_page_config(page_title="MandiMind", page_icon="🌾", layout="wide")
st.title("MandiMind")
st.caption("A small AI-agent PoC for comparing mandi prices")
st.write("Enter a crop and location. The agent checks local prices, compares markets in the state, and looks at recent price movement before giving a simple suggestion.")
with st.form("advice_form"):
    left, middle, right = st.columns(3)
    commodity = left.selectbox("Commodity", ["Onion", "Potato", "Tomato"])
    quantity = middle.number_input("Quantity in quintals", min_value=1.0, value=50.0, step=1.0)
    state = right.text_input("State", value="Maharashtra")
    district = left.text_input("District", value="Nashik")
    submitted = st.form_submit_button("Get advice", type="primary")
if submitted:
    result = MandiMindAgent().advise(commodity, quantity, state, district)
    st.info(f"Data source: {result['source']}")
    if result["source_note"]: st.warning(result["source_note"])
    st.subheader("Recommendation")
    st.success(result["recommendation"])
    if result["local_market"]:
        first, second, third = st.columns(3)
        first.metric("Local modal price", f"₹{result['local_market']['modal_price']:,.0f}/quintal", result["local_market"]["market"])
        if result["best_market"]:
            second.metric("Best alternate", f"₹{result['best_market']['modal_price']:,.0f}/quintal", result["best_market"]["market"])
        third.metric("Estimated gross difference", f"₹{result['estimated_extra_revenue']:,.0f}")
    st.caption("Gross comparison only. Transport, commission, storage, and other costs are not included.")
    st.subheader("Market comparison")
    st.dataframe([{"Market": row["market"], "District": row["district"], "Modal price (₹/quintal)": row["modal_price"], "Arrival volume": row["arrivals"] if row["arrivals"] is not None else "Not reported"} for row in result["comparison_markets"]], use_container_width=True, hide_index=True)
    st.subheader("Recent price trend")
    for trend in [item for item in (result["local_trend"], result["alternate_trend"]) if item]:
        st.write(f"**{trend['market']}**: {trend['direction'].title()} ({trend['percent_change']:+.2f}% across {trend['days']} days)")
    with st.expander("How the agent reached this answer"):
        st.write("The agent calls these tools in order. The recommendation is based on the tool results below.")
        for step, item in enumerate(result["trace"], start=1):
            st.markdown(f"**{step}. {item['tool']}**")
            st.json({"input": item["input"], "output": item["output"]})
        st.caption("Advice wording was generated by an LLM." if result["llm_used"] else "Advice wording used the built-in fallback, so this demo works without a working LLM key.")
