"""Streamlit entry point for the MandiMind PoC."""
import streamlit as st
from agent.agent import MandiMindAgent
from data.agmarknet_client import AgmarknetClient

TRANSLATIONS = {
    "English": {
        "language": "Language", "caption": "A small AI-agent PoC for comparing mandi prices",
        "intro": "Enter a crop and location. The agent checks local prices, compares markets in the state, and looks at recent price movement before giving a simple suggestion.",
        "commodity": "Commodity", "quantity": "Quantity in quintals", "state": "State", "district": "District",
        "submit": "Get advice", "source": "Data source", "recommendation": "Recommendation",
        "local_price": "Local modal price", "best_alternate": "Best alternate", "difference": "Estimated gross difference",
        "gross_note": "Gross comparison only. Transport, commission, storage, and other costs are not included.",
        "comparison": "Market comparison", "market": "Market", "market_district": "District",
        "modal_price": "Modal price (₹/quintal)", "arrivals": "Arrival volume", "not_reported": "Not reported",
        "trend": "Recent price trend", "trace": "How the agent reached this answer",
        "trace_intro": "The agent calls these tools in order. The recommendation is based on the tool results below.",
        "llm": "Advice wording was generated by an LLM.",
        "fallback": "Advice wording used the built-in fallback, so this demo works without a working LLM key.",
    },
    "Hindi": {
        "language": "भाषा", "caption": "मंडी कीमतों की तुलना के लिए एक छोटा AI एजेंट",
        "intro": "फसल और स्थान दर्ज करें। एजेंट स्थानीय कीमतों की जांच करके राज्य के बाजारों की तुलना करेगा और सुझाव देगा।",
        "commodity": "फसल", "quantity": "क्विंटल में मात्रा", "state": "राज्य", "district": "जिला", "submit": "सलाह लें",
        "source": "डेटा स्रोत", "recommendation": "सिफारिश", "local_price": "स्थानीय मॉडल कीमत", "best_alternate": "सबसे अच्छा वैकल्पिक बाजार", "difference": "अनुमानित सकल अंतर",
        "gross_note": "यह केवल सकल तुलना है। परिवहन, कमीशन, भंडारण और अन्य लागतें शामिल नहीं हैं।", "comparison": "बाजार तुलना", "market": "बाजार", "market_district": "जिला", "modal_price": "मॉडल कीमत (₹/क्विंटल)", "arrivals": "आवक", "not_reported": "उपलब्ध नहीं", "trend": "हाल की कीमत का रुझान", "trace": "एजेंट ने यह उत्तर कैसे दिया", "trace_intro": "एजेंट ने नीचे दिए गए टूल क्रम से चलाए।", "llm": "सलाह की भाषा LLM ने तैयार की है।", "fallback": "सलाह के लिए अंतर्निहित विकल्प का उपयोग किया गया है।",
    },
    "Marathi": {
        "language": "भाषा", "caption": "मंडीच्या किमतींची तुलना करण्यासाठी एक छोटा AI एजंट", "intro": "पीक आणि ठिकाण द्या. एजंट स्थानिक किमती तपासून राज्यातील बाजारांची तुलना करेल आणि सूचना देईल.", "commodity": "पीक", "quantity": "क्विंटलमधील प्रमाण", "state": "राज्य", "district": "जिल्हा", "submit": "सल्ला घ्या", "source": "डेटा स्रोत", "recommendation": "शिफारस", "local_price": "स्थानिक मॉडेल किंमत", "best_alternate": "सर्वोत्तम पर्यायी बाजार", "difference": "अंदाजे एकूण फरक", "gross_note": "ही फक्त एकूण तुलना आहे. वाहतूक, कमिशन, साठवणूक आणि इतर खर्च समाविष्ट नाहीत.", "comparison": "बाजार तुलना", "market": "बाजार", "market_district": "जिल्हा", "modal_price": "मॉडेल किंमत (₹/क्विंटल)", "arrivals": "आवक", "not_reported": "माहिती नाही", "trend": "अलीकडील किमतीचा कल", "trace": "एजंटने हे उत्तर कसे दिले", "trace_intro": "एजंटने खालील साधने क्रमाने वापरली.", "llm": "सल्ल्याची भाषा LLM ने तयार केली आहे.", "fallback": "सल्ल्यासाठी अंगभूत पर्याय वापरला आहे.",
    },
    "Telugu": {
        "language": "భాష", "caption": "మార్కెట్ ధరలను పోల్చడానికి చిన్న AI ఏజెంట్", "intro": "పంట మరియు ప్రాంతాన్ని నమోదు చేయండి. ఏజెంట్ స్థానిక ధరలను పరిశీలించి రాష్ట్రంలోని మార్కెట్లను పోల్చి సూచన ఇస్తుంది.", "commodity": "పంట", "quantity": "క్వింటాళ్లలో పరిమాణం", "state": "రాష్ట్రం", "district": "జిల్లా", "submit": "సలహా పొందండి", "source": "డేటా మూలం", "recommendation": "సిఫార్సు", "local_price": "స్థానిక మోడల్ ధర", "best_alternate": "ఉత్తమ ప్రత్యామ్నాయ మార్కెట్", "difference": "అంచనా మొత్తం తేడా", "gross_note": "ఇది మొత్తం ధరల పోలిక మాత్రమే. రవాణా, కమీషన్, నిల్వ మరియు ఇతర ఖర్చులు చేర్చబడలేదు.", "comparison": "మార్కెట్ పోలిక", "market": "మార్కెట్", "market_district": "జిల్లా", "modal_price": "మోడల్ ధర (₹/క్వింటాల్)", "arrivals": "వచ్చిన పరిమాణం", "not_reported": "సమాచారం లేదు", "trend": "ఇటీవలి ధరల ధోరణి", "trace": "ఏజెంట్ ఈ సమాధానాన్ని ఎలా ఇచ్చింది", "trace_intro": "ఏజెంట్ క్రింది సాధనాలను క్రమంగా ఉపయోగించింది.", "llm": "సలహా భాషను LLM రూపొందించింది.", "fallback": "LLM కీ లేకపోయినా పనిచేయడానికి అంతర్నిర్మిత సలహాను ఉపయోగించారు.",
    },
    "Tamil": {
        "language": "மொழி", "caption": "சந்தை விலைகளை ஒப்பிடும் சிறிய AI முகவர்", "intro": "பயிர் மற்றும் இடத்தை உள்ளிடுங்கள். முகவர் உள்ளூர் விலைகளைச் சரிபார்த்து மாநில சந்தைகளை ஒப்பிட்டு ஆலோசனை வழங்கும்.", "commodity": "பயிர்", "quantity": "குவிண்டால்களில் அளவு", "state": "மாநிலம்", "district": "மாவட்டம்", "submit": "ஆலோசனை பெறுக", "source": "தரவு மூலம்", "recommendation": "பரிந்துரை", "local_price": "உள்ளூர் மாடல் விலை", "best_alternate": "சிறந்த மாற்றுச் சந்தை", "difference": "மதிப்பிடப்பட்ட மொத்த வித்தியாசம்", "gross_note": "இது மொத்த விலை ஒப்பீடு மட்டுமே. போக்குவரத்து, கமிஷன், சேமிப்பு மற்றும் பிற செலவுகள் சேர்க்கப்படவில்லை.", "comparison": "சந்தை ஒப்பீடு", "market": "சந்தை", "market_district": "மாவட்டம்", "modal_price": "மாடல் விலை (₹/குவிண்டால்)", "arrivals": "வரத்து அளவு", "not_reported": "தகவல் இல்லை", "trend": "சமீபத்திய விலை போக்கு", "trace": "முகவர் இந்த பதிலை எவ்வாறு வழங்கியது", "trace_intro": "முகவர் கீழே உள்ள கருவிகளை வரிசையாகப் பயன்படுத்தியது.", "llm": "ஆலோசனை மொழியை LLM உருவாக்கியது.", "fallback": "LLM விசை இல்லாமலும் செயல்பட உள்ளமைந்த ஆலோசனை பயன்படுத்தப்பட்டது.",
    },
    "Kannada": {
        "language": "ಭಾಷೆ", "caption": "ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳನ್ನು ಹೋಲಿಸುವ ಸಣ್ಣ AI ಏಜೆಂಟ್", "intro": "ಬೆಳೆ ಮತ್ತು ಸ್ಥಳವನ್ನು ನಮೂದಿಸಿ. ಏಜೆಂಟ್ ಸ್ಥಳೀಯ ಬೆಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ರಾಜ್ಯದ ಮಾರುಕಟ್ಟೆಗಳನ್ನು ಹೋಲಿಸಿ ಸಲಹೆ ನೀಡುತ್ತದೆ.", "commodity": "ಬೆಳೆ", "quantity": "ಕ್ವಿಂಟಾಲ್‌ಗಳಲ್ಲಿ ಪ್ರಮಾಣ", "state": "ರಾಜ್ಯ", "district": "ಜಿಲ್ಲೆ", "submit": "ಸಲಹೆ ಪಡೆಯಿರಿ", "source": "ಡೇಟಾ ಮೂಲ", "recommendation": "ಶಿಫಾರಸು", "local_price": "ಸ್ಥಳೀಯ ಮಾದರಿ ಬೆಲೆ", "best_alternate": "ಅತ್ಯುತ್ತಮ ಪರ್ಯಾಯ ಮಾರುಕಟ್ಟೆ", "difference": "ಅಂದಾಜು ಒಟ್ಟು ವ್ಯತ್ಯಾಸ", "gross_note": "ಇದು ಒಟ್ಟು ಬೆಲೆ ಹೋಲಿಕೆ ಮಾತ್ರ. ಸಾರಿಗೆ, ಕಮಿಷನ್, ಸಂಗ್ರಹಣೆ ಮತ್ತು ಇತರ ವೆಚ್ಚಗಳನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ.", "comparison": "ಮಾರುಕಟ್ಟೆ ಹೋಲಿಕೆ", "market": "ಮಾರುಕಟ್ಟೆ", "market_district": "ಜಿಲ್ಲೆ", "modal_price": "ಮಾದರಿ ಬೆಲೆ (₹/ಕ್ವಿಂಟಾಲ್)", "arrivals": "ಆಗಮನ ಪ್ರಮಾಣ", "not_reported": "ಮಾಹಿತಿ ಇಲ್ಲ", "trend": "ಇತ್ತೀಚಿನ ಬೆಲೆ ಪ್ರವೃತ್ತಿ", "trace": "ಏಜೆಂಟ್ ಈ ಉತ್ತರವನ್ನು ಹೇಗೆ ನೀಡಿತು", "trace_intro": "ಏಜೆಂಟ್ ಕೆಳಗಿನ ಸಾಧನಗಳನ್ನು ಕ್ರಮವಾಗಿ ಬಳಸಿದೆ.", "llm": "ಸಲಹೆಯ ಭಾಷೆಯನ್ನು LLM ರಚಿಸಿದೆ.", "fallback": "LLM ಕೀ ಇಲ್ಲದಿದ್ದರೂ ಕೆಲಸ ಮಾಡಲು ಅಂತರ್ನಿರ್ಮಿತ ಸಲಹೆಯನ್ನು ಬಳಸಲಾಗಿದೆ.",
    },
    "Malayalam": {
        "language": "ഭാഷ", "caption": "വിപണി വിലകൾ താരതമ്യം ചെയ്യാനുള്ള ചെറിയ AI ഏജന്റ്", "intro": "വിളയും സ്ഥലവും നൽകുക. ഏജന്റ് പ്രാദേശിക വിലകൾ പരിശോധിച്ച് സംസ്ഥാനത്തെ വിപണികൾ താരതമ്യം ചെയ്ത് നിർദ്ദേശം നൽകും.", "commodity": "വിള", "quantity": "ക്വിന്റലുകളിലെ അളവ്", "state": "സംസ്ഥാനം", "district": "ജില്ല", "submit": "നിർദ്ദേശം നേടുക", "source": "ഡാറ്റാ ഉറവിടം", "recommendation": "ശുപാർശ", "local_price": "പ്രാദേശിക മോഡൽ വില", "best_alternate": "മികച്ച ബദൽ വിപണി", "difference": "കണക്കാക്കിയ മൊത്തം വ്യത്യാസം", "gross_note": "ഇത് മൊത്തം വില താരതമ്യം മാത്രമാണ്. ഗതാഗതം, കമ്മീഷൻ, സംഭരണം, മറ്റ് ചെലവുകൾ എന്നിവ ഉൾപ്പെടുത്തിയിട്ടില്ല.", "comparison": "വിപണി താരതമ്യം", "market": "വിപണി", "market_district": "ജില്ല", "modal_price": "മോഡൽ വില (₹/ക്വിന്റൽ)", "arrivals": "വരവ് അളവ്", "not_reported": "വിവരമില്ല", "trend": "സമീപകാല വിലാ പ്രവണത", "trace": "ഏജന്റ് ഈ ഉത്തരം എങ്ങനെ നൽകി", "trace_intro": "ഏജന്റ് താഴെയുള്ള ഉപകരണങ്ങൾ ക്രമത്തിൽ ഉപയോഗിച്ചു.", "llm": "ഉപദേശത്തിന്റെ ഭാഷ LLM തയ്യാറാക്കി.", "fallback": "LLM കീ ഇല്ലാതെയും പ്രവർത്തിക്കാൻ അന്തർനിർമ്മിത ഉപദേശം ഉപയോഗിച്ചു.",
    },
}

LANGUAGE_NAMES = list(TRANSLATIONS)

st.set_page_config(page_title="MandiMind", page_icon="🌾", layout="wide")


language = st.sidebar.selectbox("Language / भाषा", LANGUAGE_NAMES)
text = TRANSLATIONS[language]
st.title("MandiMind")
st.caption(text["caption"])
st.write(text["intro"])
with st.form("advice_form"):
    left, middle, right = st.columns(3)
    state = right.text_input(text["state"], value="Maharashtra")
    commodity_options = AgmarknetClient().commodities_for_state(state)
    commodity = left.selectbox(text["commodity"], commodity_options)
    quantity = middle.number_input(text["quantity"], min_value=1.0, value=50.0, step=1.0)
    district = left.text_input(text["district"], value="Nashik")
    submitted = st.form_submit_button(text["submit"], type="primary")
if submitted:
    result = MandiMindAgent().advise(commodity, quantity, state, district, language)
    st.info(f"{text['source']}: {result['source']}")
    if result["source_note"]: st.warning(result["source_note"])
    st.subheader(text["recommendation"])
    st.success(result["recommendation"])
    if result["local_market"]:
        first, second, third = st.columns(3)
        first.metric(text["local_price"], f"₹{result['local_market']['modal_price']:,.0f}/quintal", result['local_market']['market'])
        if result["best_market"]:
            second.metric(text["best_alternate"], f"₹{result['best_market']['modal_price']:,.0f}/quintal", result['best_market']['market'])
        third.metric(text["difference"], f"₹{result['estimated_extra_revenue']:,.0f}")
    st.caption(text["gross_note"])
    st.subheader(text["comparison"])
    st.dataframe([{text["market"]: row["market"], text["market_district"]: row["district"], text["modal_price"]: row["modal_price"], text["arrivals"]: row["arrivals"] if row["arrivals"] is not None else text["not_reported"]} for row in result["comparison_markets"]], use_container_width=True, hide_index=True)
    st.subheader(text["trend"])
    for trend in [item for item in (result["local_trend"], result["alternate_trend"]) if item]:
        st.write(f"**{trend['market']}**: {trend['direction'].title()} ({trend['percent_change']:+.2f}% across {trend['days']} days)")
    with st.expander(text["trace"]):
        st.write(text["trace_intro"])
        for step, item in enumerate(result["trace"], start=1):
            st.markdown(f"**{step}. {item['tool']}**")
            st.json({"input": item["input"], "output": item["output"]})
        st.caption(text["llm"] if result["llm_used"] else text["fallback"])
